services:

  db:
    image: postgres:18.1-alpine
    labels:
      org.springframework.boot.service.name: "taska-db"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_DB: taska
      POSTGRES_USER: taska
      POSTGRES_PASSWORD: taska
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
