package com.taska.domain.task;

import org.springframework.data.jpa.repository.JpaRepository;

import java.time.Instant;
import java.util.Collection;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * Repository for {@link TaskInstance} — persisted occurrences of recurring tasks.
 */
public interface TaskInstanceRepository extends JpaRepository<TaskInstance, UUID> {

    /**
     * Returns all instances for the given recurring tasks whose {@code scheduledAt} falls within
     * [{@code from}, {@code to}]. Used during occurrence expansion to overlay persisted state
     * (DONE/SKIPPED/MODIFIED) onto the virtually generated occurrence list.
     */
    List<TaskInstance> findByTaskIdInAndScheduledAtBetween(Collection<UUID> taskIds, Instant from, Instant to);

    /**
     * Returns the persisted instance for a specific task occurrence, identified by the task ID and
     * the exact {@code scheduledAt} instant generated by the RRULE.
     */
    Optional<TaskInstance> findByTaskIdAndScheduledAt(UUID taskId, Instant scheduledAt);

    /**
     * Deletes the instance for a specific occurrence. Used when reopening a completed recurring
     * occurrence to restore it to its virtual (open) state.
     */
    void deleteByTaskIdAndScheduledAt(UUID taskId, Instant scheduledAt);

    /**
     * Returns all MODIFIED instances for the given tasks whose {@code dueAt} falls within
     * [{@code from}, {@code to}]. Used to surface occurrences that were rescheduled into the
     * queried period from a different day.
     */
    List<TaskInstance> findByTaskIdInAndStatusAndDueAtBetween(
            Collection<UUID> taskIds, TaskInstanceStatus status, Instant from, Instant to);

    /** Returns all persisted instances for the given recurring task, regardless of their status. */
    List<TaskInstance> findByTaskId(UUID taskId);
}
