package com.taska.domain.task;

import org.springframework.data.jpa.repository.JpaRepository;

import java.time.Instant;
import java.util.Collection;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * Repository for {@link TaskInstance} — persisted occurrences of recurring tasks.
 */
public interface TaskInstanceRepository extends JpaRepository<TaskInstance, UUID> {

    /**
     * Returns all instances for the given recurring tasks whose {@code occurrenceScheduledAt} falls within
     * [{@code from}, {@code to}]. Used during occurrence expansion to overlay persisted state
     * (DONE/SKIPPED/MODIFIED) onto the virtually generated occurrence list.
     */
    List<TaskInstance> findByTaskIdInAndOccurrenceScheduledAtBetween(Collection<UUID> taskIds, Instant from, Instant to);

    /**
     * Returns the persisted instance for a specific task occurrence, identified by the task ID and
     * the exact {@code occurrenceScheduledAt} instant generated by the RRULE.
     */
    Optional<TaskInstance> findByTaskIdAndOccurrenceScheduledAt(UUID taskId, Instant occurrenceScheduledAt);

    /**
     * Deletes the instance for a specific occurrence. Used when reopening a completed recurring
     * occurrence to restore it to its virtual (open) state.
     */
    void deleteByTaskIdAndOccurrenceScheduledAt(UUID taskId, Instant occurrenceScheduledAt);

    /**
     * Returns all MODIFIED instances for the given tasks whose {@code scheduledAt} falls within
     * [{@code from}, {@code to}]. Used to surface occurrences that were rescheduled into the
     * queried period from a different day. This is the occurrence's planned-time override,
     * not its {@code occurrenceScheduledAt} identity.
     */
    List<TaskInstance> findByTaskIdInAndStatusAndScheduledAtBetween(
            Collection<UUID> taskIds, TaskInstanceStatus status, Instant from, Instant to);
}
