package com.taska.domain.task;

import java.time.Instant;

/**
 * Request payload for closing (completing) or reopening a task occurrence.
 *
 * @param occurrenceScheduledAt for recurring tasks, the UTC instant identifying the specific occurrence
 *                    to close or reopen; required when the task is recurring,
 *                    and must match a valid occurrence generated by the task's RRULE
 */
public record TaskCloseReopenRequest(Instant occurrenceScheduledAt) {}
