package com.taska.domain.planningcalendar;
import com.taska.config.TaskaProperties; import com.taska.exception.ResourceNotFoundException; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.Instant; import java.time.ZoneId; import java.util.*;
@Service @Transactional @RequiredArgsConstructor public class PlanningCalendarService {
 public static final UUID DEFAULT_ID=UUID.fromString("00000000-0000-0000-0000-000000000001"); private final PlanningCalendarRepository calendars; private final PlanningCalendarRuleRepository rules; private final TaskaProperties properties;
 @Transactional(readOnly=true) public List<PlanningCalendarDto> all(){return calendars.findAll().stream().map(this::dto).toList();}
 @Transactional(readOnly=true) public PlanningCalendarDto get(UUID id){return dto(entity(id));}
 public PlanningCalendarDto create(PlanningCalendarRequest r){var c=new PlanningCalendar();c.setName(r.name());var saved=calendars.save(c); replace(saved.getId(),r.rules());return get(saved.getId());}
 public PlanningCalendarDto update(UUID id,PlanningCalendarRequest r){var c=entity(id);c.setName(r.name());calendars.save(c);if(r.rules()!=null)replace(id,r.rules());return get(id);}
 public boolean allows(UUID id,Instant at,boolean allDay){var z=properties.getCalendar().getTimeZone();var l=at.atZone(z);var rs=rules.findByCalendarIdOrderByDayOfWeekAscStartMinuteAsc(id); if(allDay)return rs.stream().anyMatch(r->r.getDayOfWeek()==l.getDayOfWeek().getValue()); int m=l.getHour()*60+l.getMinute();return rs.stream().anyMatch(r->r.getDayOfWeek()==l.getDayOfWeek().getValue()&&r.getStartMinute()<=m&&m<r.getEndMinute());}
 private void replace(UUID id,List<PlanningCalendarRequest.Rule> in){if(in==null)return;validate(in);rules.deleteByCalendarId(id);rules.saveAll(in.stream().map(x->{var r=new PlanningCalendarRule();r.setCalendarId(id);r.setDayOfWeek(x.dayOfWeek());r.setStartMinute(x.startMinute());r.setEndMinute(x.endMinute());return r;}).toList());}
 private void validate(List<PlanningCalendarRequest.Rule> x){for(var r:x)if(r.dayOfWeek()<1||r.dayOfWeek()>7||r.startMinute()<0||r.startMinute()>=r.endMinute()||r.endMinute()>1440)throw new IllegalArgumentException("Invalid availability rule"); for(int d=1;d<=7;d++){final int day=d;var a=x.stream().filter(r->r.dayOfWeek()==day).sorted(Comparator.comparingInt(PlanningCalendarRequest.Rule::startMinute)).toList();for(int i=1;i<a.size();i++)if(a.get(i-1).endMinute()>a.get(i).startMinute())throw new IllegalArgumentException("Availability rules overlap");}}
 private PlanningCalendar entity(UUID id){return calendars.findById(id).orElseThrow(()->new ResourceNotFoundException("Planning calendar not found: "+id));} private PlanningCalendarDto dto(PlanningCalendar c){return new PlanningCalendarDto(c.getId(),c.getName(),rules.findByCalendarIdOrderByDayOfWeekAscStartMinuteAsc(c.getId()).stream().map(r->new PlanningCalendarDto.Rule(r.getDayOfWeek(),r.getStartMinute(),r.getEndMinute())).toList());}
}
