package com.taska.domain.task.occurrence.repository;

import com.taska.domain.task.occurrence.TaskOccurrenceState;
import com.taska.domain.task.occurrence.TaskOccurrenceStatus;
import java.time.Instant;
import java.util.Collection;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.data.jpa.repository.JpaRepository;

/** Repository for sparse {@link TaskOccurrenceState} attached to recurring task occurrences. */
public interface TaskOccurrenceStateRepository extends JpaRepository<TaskOccurrenceState, UUID> {

  /**
   * Returns all persisted states for the given recurring series whose {@code occurrenceScheduledAt}
   * falls within [{@code from}, {@code to}]. Used during occurrence expansion to overlay
   * DONE/SKIPPED/MODIFIED state onto the virtually generated occurrences.
   */
  List<TaskOccurrenceState> findBySeriesIdInAndOccurrenceScheduledAtBetween(
      Collection<UUID> seriesIds, Instant from, Instant to);

  /**
   * Returns the persisted state for a specific occurrence, identified by the series ID and the
   * exact {@code occurrenceScheduledAt} instant generated by the RRULE.
   */
  Optional<TaskOccurrenceState> findBySeriesIdAndOccurrenceScheduledAt(
      UUID seriesId, Instant occurrenceScheduledAt);

  /**
   * Deletes the persisted state for a specific occurrence. Used when reopening a completed
   * recurring occurrence to restore it to its virtual (open) state.
   */
  void deleteBySeriesIdAndOccurrenceScheduledAt(UUID seriesId, Instant occurrenceScheduledAt);

  /**
   * Returns all MODIFIED states for the given series whose {@code scheduledAt} falls within [{@code
   * from}, {@code to}]. Used to surface occurrences that were rescheduled into the queried period
   * from a different day. This is the occurrence's planned-time override, not its {@code
   * occurrenceScheduledAt} identity.
   */
  List<TaskOccurrenceState> findBySeriesIdInAndStatusAndScheduledAtBetween(
      Collection<UUID> seriesIds, TaskOccurrenceStatus status, Instant from, Instant to);

  /**
   * Returns all states with the requested status whose effective schedule falls within the given
   * window. Used by notification discovery so an occurrence moved into the window remains visible
   * even when its backing series does not otherwise overlap that window.
   */
  List<TaskOccurrenceState> findByStatusAndScheduledAtBetween(
      TaskOccurrenceStatus status, Instant from, Instant to);
}
