package com.taska.domain.task.occurrence.repository;

import com.taska.domain.task.occurrence.TaskOccurrenceStatus;
import java.time.Instant;
import java.util.Collection;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

/** Repository for sparse {@link TaskOccurrenceState} attached to recurring task occurrences. */
public interface TaskOccurrenceStateRepository extends JpaRepository<TaskOccurrenceState, UUID> {

  /** Returns whether the recurring series has any persisted occurrence state. */
  boolean existsBySeriesId(UUID seriesId);

  /**
   * Returns all persisted states for the given recurring series whose {@code occurrenceScheduledAt}
   * falls within [{@code from}, {@code to}]. Used during occurrence expansion to overlay
   * DONE/SKIPPED/MODIFIED state onto the virtually generated occurrences.
   */
  List<TaskOccurrenceState> findBySeriesIdInAndOccurrenceScheduledAtBetween(
      Collection<UUID> seriesIds, Instant from, Instant to);

  /**
   * Returns the persisted state for a specific occurrence, identified by the series ID and the
   * exact {@code occurrenceScheduledAt} instant generated by the RRULE.
   */
  Optional<TaskOccurrenceState> findBySeriesIdAndOccurrenceScheduledAt(
      UUID seriesId, Instant occurrenceScheduledAt);

  /**
   * Deletes the persisted state for a specific occurrence. Used when reopening a completed
   * recurring occurrence to restore it to its virtual (open) state.
   */
  void deleteBySeriesIdAndOccurrenceScheduledAt(UUID seriesId, Instant occurrenceScheduledAt);

  /**
   * Returns all MODIFIED states for the given series whose {@code scheduledAt} falls within [{@code
   * from}, {@code to}]. Used to surface occurrences that were rescheduled into the queried period
   * from a different day. This is the occurrence's planned-time override, not its {@code
   * occurrenceScheduledAt} identity.
   */
  List<TaskOccurrenceState> findBySeriesIdInAndStatusAndScheduledAtBetween(
      Collection<UUID> seriesIds, TaskOccurrenceStatus status, Instant from, Instant to);

  /**
   * Returns all states with the requested status whose effective schedule falls within the given
   * window. Used by notification discovery so an occurrence moved into the window remains visible
   * even when its backing series does not otherwise overlap that window.
   */
  List<TaskOccurrenceState> findByStatusAndScheduledAtBetween(
      TaskOccurrenceStatus status, Instant from, Instant to);

  /**
   * Returns every state of one series anchored at or after the given instant, that is every state a
   * truncation at that instant leaves without a generated occurrence.
   *
   * @param seriesId recurring-series identifier
   * @param occurrenceScheduledAt inclusive lower bound on the anchor
   * @return the states the truncation strands
   */
  List<TaskOccurrenceState> findBySeriesIdAndOccurrenceScheduledAtGreaterThanEqual(
      UUID seriesId, Instant occurrenceScheduledAt);

  /**
   * Returns detached states falling inside the period by their effective date, which is their own
   * scheduled override when they carry one and their anchor otherwise.
   *
   * <p>Deliberately not restricted to series that are still active over the period: a detached
   * state outlives the stretch of time its series generates, which is precisely what detaches it.
   *
   * @param periodStart inclusive start of the period
   * @param periodEnd exclusive end of the period
   * @return the detached states to display over that period
   */
  @Query(
      """
      SELECT state FROM TaskOccurrenceState state
      WHERE state.detached = true
      AND COALESCE(state.scheduledAt, state.occurrenceScheduledAt) >= :periodStart
      AND COALESCE(state.scheduledAt, state.occurrenceScheduledAt) < :periodEnd
      """)
  List<TaskOccurrenceState> findDetachedInPeriod(
      @Param("periodStart") Instant periodStart, @Param("periodEnd") Instant periodEnd);
}
