app:
  version: '@app.version@'

spring:
  application:
    name: taska-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/taska
    username: taska
    password: taska
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/application/o/taska/
