spring.application.name=taska-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/taska
spring.datasource.username=taska
spring.datasource.password=taska
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://192.168.1.14:8000/application/o/taska/

springdoc.swagger-ui.enabled=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.datatype.datetime.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

taska.notification.scheduler-delay=60000