spring.application.name=taska-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/taska
spring.datasource.username=taska
spring.datasource.password=taska
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://192.168.1.14:8000/application/o/taska/

taska.notification.scheduler-delay=60000