spring.security.oauth2.resourceserver.jwt.issuer-uri=http://192.168.1.104:8000/application/o/taska/

taska.security.increase-timeout=true
taska.security.disable-issuer-validation=true

taska.notification.scheduler-delay=5000
taska.notification.enabled=false

taska.priority-evaluation.scheduler-delay=5000

logging.level.com.taska.domain.notification=INFO