taska.security.increase-timeout=true
taska.security.disable-issuer-validation=true

taska.notification.scheduler-delay=5000
taska.notification.enabled=false

taska.priority-evaluation.scheduler-delay=5000

logging.level.com.taska.domain.notification=INFO