name: Release

on:
  push:
    tags: ["*"]

jobs:
  frontend-backend:
    if: "!contains(github.ref_name, '-tauri') && !contains(github.ref_name, '-android')"
    uses: ./.github/workflows/build-frontend-backend.yml
    permissions:
      contents: read
      packages: write
    secrets: inherit

  tauri:
    if: "!contains(github.ref_name, '-android')"
    uses: ./.github/workflows/build-tauri.yml
    permissions:
      contents: write
    secrets: inherit

  android:
    if: "!contains(github.ref_name, '-tauri')"
    uses: ./.github/workflows/build-android.yml
    permissions:
      contents: write
    secrets: inherit

  deploy-portainer:
    needs: frontend-backend
    if: "!contains(github.ref_name, '-tauri') && !contains(github.ref_name, '-android')"
    uses: ./.github/workflows/deploy-portainer.yml
    with:
      version: ${{ github.ref_name }}
    secrets: inherit